# Generated by Django 3.2.6 on 2021-12-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=40)),
                ('FullName', models.CharField(max_length=40)),
                ('City', models.CharField(max_length=40)),
                ('Salary', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
