# Generated by Django 3.2.6 on 2021-09-21 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'employee',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200)),
                ('exp', models.CharField(max_length=200)),
                ('empid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app1.employee')),
            ],
            options={
                'verbose_name_plural': 'Dept',
                'db_table': 'dept',
            },
        ),
    ]
